app/redes_servicios/models.py
# creacion de la base de datos en caso de no existir

app/redes_servicios/nodos/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AgregarNodoForm(FlaskForm):
    
    nombre_nodo = StringField("Nombre del Nodo")
    ip_nodo = StringField("IP del Nodo")
    peid_nodo = StringField("PEID del Nodo")
    submit = SubmitField()


class EliminarNodoForm(FlaskForm):
    
    
    id_nodo = StringField("ID del Nodo")
    

app/redes_servicios/__init__.py
# __init__.py hijo directo del directorio del proyecto

from flask import  Flask
import mysql.connector
from flask_mysqldb import MySQL


app = Flask(__name__)
mysql = MySQL(app)

app.config['SECRET_KEY'] = "secretkey1"
app.config['MYSQL_HOST'] = 'mysql_app_oficial'
app.config['MYSQL_USER'] = 'root'
app.config['MYSQL_PASSWORD'] = 'root'
app.config['MYSQL_DB'] = 'red_telecom'

from redes_servicios import routes

from redes_servicios.nodos.views import nodos_blueprints

app.register_blueprint(nodos_blueprints, url_prefix='/nodos')

app/redes_servicios/nodos/views.py
# 
from flask import Blueprint, render_template, redirect, url_for
from redes_servicios import mysql
from redes_servicios.nodos.forms import AgregarNodoForm,EliminarNodoForm
import MySQLdb.cursors

nodos_blueprints = Blueprint('nodos', __name__, template_folder='templates/nodos')

@nodos_blueprints.route("/agregar", methods=['POST','GET'])
def agregar():

    form = AgregarNodoForm()

    if form.validate_on_submit():
        nombre_nodo = form.nombre_nodo.data
        ip_nodo = form.ip_nodo.data
        peid_nodo = form.peid_nodo.data

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM nodo WHERE nombre_nodo =%s', (nombre_nodo, ))        
        nodo = cursor.fetchone()

        if nodo:
            msg = 'Nodo ya existente'

        else:
            
            cursor.execute('INSERT INTO nodo VALUES (null, %s, %s, %s)', (nombre_nodo, ip_nodo, peid_nodo, ))
            
            mysql.connection.commit()

            msg = 'Nodo Agregado correctamente'

            return redirect(url_for("nodos.listar"))

    return render_template('agregar_nodo.html', form = form)


@nodos_blueprints.route("/listar", methods=['POST','GET'])
def listar():
    cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute('SELECT * FROM nodo')        
    nodos = cursor.fetchall()

    return render_template('listar.html', nodos=nodos)



            
        

app/redes_servicios/routes.py
# Lista de rutas del URL

from flask import render_template,send_file 
from redes_servicios import app
from .plot_functions.Plot_functions import determinar_migracion
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

import matplotlib.patches as mpatches
import io

import pandas as pd

# http://192.168.0.61:8000/
# http://192.168.0.61:8000/inicio
@app.route('/inicio')
@app.route('/')
def home():
    return render_template('index.html')


@app.route('/nodos')
def nodos():
    return render_template('nodos.html') 


@app.route('/migracion_personal')
def migracion_personal():
    fig, ax = plt.subplots(figsize=(6,6))

    df = pd.read_csv('redes_servicios/despliegues/migracion_personal/FUSION_FINAL_29_12_2022.csv', 
                    names=['NODO','VENDOR','VRF','INTERFACE','ESTADO'],
                    sep=';')

    df['migracion'] = df['VRF'].apply(determinar_migracion)

    color = ['green', 'red']
    df.groupby(['NODO'])['migracion'].value_counts().unstack().plot.barh(figsize=(15,25),color =color )
    plt.grid(True)
    plt.xlabel('CANTIDAD')
    plt.ylabel('NODO(S)')
    
    green_patch = mpatches.Patch(color='green', label='MIGRADAS')
    red_patch = mpatches.Patch(color='red', label='NO MIGRADAS')
    plt.legend(handles=[green_patch, red_patch])

    canvas = FigureCanvas(fig)
    img = io.BytesIO()
    
    plt.savefig(img, format="png") 
    plt.show()
    img.seek(0)
    return send_file(img, mimetype='image/png')  

app/redes_servicios/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{{url_for('static', filename = 'css/bootstrap.min.css')}}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>


<!-- NAVBAR href="{{ url_for('home') }}" -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('home') }}">Herramientas R&S</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            NODOS
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{{ url_for('nodos.listar') }}">LISTAR</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{ url_for('nodos.agregar') }}">AGREGAR</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="">Eliminar</a></li>
            
          </ul>

        </li>



        <li class="nav-item">
          <a class="nav-link" href="">herramienta 1</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Lista de Herramientas
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="">Herramienta 1</a></li>
            <li><a class="dropdown-item" href="{{ url_for('migracion_personal') }}">Consultas proyectos</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="">Herramienta 3</a></li>
          </ul>

        </li>

        <li class="nav-item">
          <a class="nav-link disabled">Link</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Búsqueda" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Búsqueda</button>
      </form>
    </div>
  </div>
</nav>
<!-- NAVBAR -->
   
    {% block content %}
      
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/redes_servicios/templates/index.html
{% extends 'base.html' %}

{% block content %}


estoy en tco oficial



{% endblock %}

app/redes_servicios/templates/nodos.html
{% extends 'base.html' %}

{% block content %}


estoy en tco nodos

<h1>Gráfica: Estado de migración</h1>
<div>
                  
    <img src="{{url_for( 'visualize') }}">
    
</div>

{% endblock %}